### ISSUE TITLE
Build fail after rebased with master

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/gdscript-tests#1]
seems like `gdscript_test.cpp` need to be updated with `Callable`. here is the failed build log
```
1>gdscript_test.cpp
1>modules\gdscript\gdscript_test.cpp(385): error C2039: 'get_ref_ptr': is not a member of 'Ref<GDScript>'
1>C:\dev\godot\modules\gdscript\gdscript.h(77): note: see declaration of 'Ref<GDScript>'
1>modules\gdscript\gdscript_test.cpp(397): error C2039: 'CallError': is not a member of 'Variant'
1>C:\dev\godot\core/variant.h(70): note: see declaration of 'Variant'
1>modules\gdscript\gdscript_test.cpp(397): error C2065: 'CallError': undeclared identifier
1>modules\gdscript\gdscript_test.cpp(397): error C2146: syntax error: missing ';' before identifier 'call_err'
1>modules\gdscript\gdscript_test.cpp(397): error C2065: 'call_err': undeclared identifier
1>modules\gdscript\gdscript_test.cpp(398): error C2065: 'call_err': undeclared identifier
1>modules\gdscript\gdscript_test.cpp(405): error C2065: 'call_err': undeclared identifier
1>modules\gdscript\gdscript_test.cpp(405): error C3083: 'CallError': the symbol to the left of a '::' must be a type
1>modules\gdscript\gdscript_test.cpp(405): error C2039: 'CALL_OK': is not a member of 'Variant'
1>C:\dev\godot\core/variant.h(70): note: see declaration of 'Variant'
1>modules\gdscript\gdscript_test.cpp(405): error C2065: 'CALL_OK': undeclared identifier
1>scons: *** [modules\gdscript\gdscript_test.windows.tools.64.obj] Error 2
1>scons: building terminated because of errors.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "echo Starting SCons && cmd /V /C set "plat=x64" ^& (if "x64"=="x64" (set "plat=x86_amd64")) ^& set "tools=yes" ^& (if "debug"=="release" (set "tools=no")) ^& call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" !plat! ^& scons --directory="C:\dev\godot" platform=windows progress=no target=debug tools=!tools! -j1" exited with code 2.
1>Done building project "godot.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by ThakeeNathees** [comment]
will this repository be use to test the new parser ??
